Сделал экран для хранения документов и экран с текст вью для отображе…
InnoProg-Project/my_startup pull request #100
Opened 2024-03-31 13:03 UTC by Bivis63

…ния документов.

2024-04-01 06:53 UTC, n-shvedov27 requested changes

2024-04-01 06:53 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/profile/legaldocuments/presentation/DocumentFragment.kt
> +class DocumentFragment : Fragment() {
Почему не BaseFragment?

2024-04-01 06:53 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_document.xml
> +        <com.innoprog.android.uikit.InnoProgTopBarView
А как этот файл с апи приходит? Говорил с заказчиком?

<img width="181" alt="Снимок экрана 2024-04-01 в 11 51 24" src="https://github.com/InnoProg-Project/InnoProg/assets/37715977/0e3c48d7-aa83-4a2b-bf5d-7fc13fd8bb4a">

2024-04-01 06:58 UTC, n-shvedov27 requested changes
Этот фрагмент должен отображаться без BottomNavigationView
![photo_2024-04-01 11 57 11](https://github.com/InnoProg-Project/InnoProg/assets/37715977/eab3c86a-a89a-46f1-a385-ef561bb1ba4f)

<img width="236" alt="Снимок экрана 2024-04-01 в 11 57 37" src="https://github.com/InnoProg-Project/InnoProg/assets/37715977/fad1dede-3b3f-4148-83f0-ae291ee58f44">

2024-04-01 07:06 UTC, Bivis63 commented on app/src/main/java/com/innoprog/android/feature/profile/legaldocuments/presentation/DocumentFragment.kt
> +class DocumentFragment : Fragment() {
Я подумал что нам там viewModel не понадобится , решил оставить фрагмент

2024-04-01 07:11 UTC, Bivis63 commented on app/src/main/res/layout/fragment_document.xml
> +        <com.innoprog.android.uikit.InnoProgTopBarView
я наверно не совсем корректно задал вопрос заказчику. Я спросил должен ли весь текст из файла отображаться в текст вью на фрагменте Document, они ответили что должен. Т.е файл не выкачивается на устройство, а открывается в новом фрагменте. А как это уже будет реализовано не обсуждалось. Я думаю что нужно будет загружать файл и как то передавать от туда текст в фрагмент Document

2024-04-03 04:22 UTC, n-shvedov27 requested changes
Ждем [фикса навигации](https://github.com/InnoProg-Project/InnoProg/issues/101)

2024-04-04 05:48 UTC, n-shvedov27 approved these changes

2024-04-04 05:48 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_document.xml
> +        <com.innoprog.android.uikit.InnoProgTopBarView
Если честно кажется что это дичь какая-то
Ну ладно пока с апи что-то не получим, не понятно как оно реально должно работать

2024-04-04 05:49 UTC, merged