33 31  reg
InnoProg-Project/my_startup pull request #107
Opened 2024-04-07 12:10 UTC by AntaOtk

разметка экрана регистрации

2024-04-09 19:39 UTC, Bivis63 requested changes

2024-04-09 19:39 UTC, Bivis63 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/presentation/RegistrationViewModel.kt
> +        } else processResult(Pair(false, "не все поля заполнены"))
давай вынесем в ресурсы?

2024-04-09 19:39 UTC, Bivis63 commented on app/src/main/res/layout/fragment_registration.xml
> +        app:topBar_title="Регистрация" />
и регистрацию давай тоже вынесем в ресурсы и сольём )

2024-04-15 05:56 UTC, n-shvedov27 requested changes
Чето с back-навигацией не то по-моему

https://github.com/InnoProg-Project/InnoProg/assets/37715977/4e1aceca-2e0c-4e71-bbe8-ee1f9333bfc5

2024-04-17 05:28 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/presentation/RegistrationViewModel.kt
> +        } else processResult(Pair(false, "не все поля заполнены"))
Поправь еще этот коммент и сольем

2024-04-17 05:29 UTC, n-shvedov27 requested changes
Поправь еще [этот](https://github.com/InnoProg-Project/InnoProg/pull/107#discussion_r1555990334) коммент и сольем

2024-04-17 07:33 UTC, AntaOtk commented on app/src/main/java/com/innoprog/android/feature/auth/registration/presentation/RegistrationViewModel.kt
> +        } else processResult(Pair(false, "не все поля заполнены"))
тут у меня главный затык прикрутить context или какой-нибудь класс ResourcesProvider через даггер.

2024-04-17 09:44 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/presentation/RegistrationViewModel.kt
> +        } else processResult(Pair(false, "не все поля заполнены"))
Можно RegistrationComponent сделать зависимым от AppComponent, который уже предоставляет app (context)

2024-04-19 06:00 UTC, n-shvedov27 approved these changes

2024-04-19 06:01 UTC, n-shvedov27 requested changes
Конфликты

2024-04-19 17:13 UTC, Bivis63 approved these changes

2024-04-23 11:57 UTC, NadezhdaSakal approved these changes

2024-04-24 06:31 UTC, n-shvedov27 approved these changes

2024-04-25 05:19 UTC, merged