34 recovery pass
InnoProg-Project/my_startup pull request #114
Opened 2024-04-09 15:49 UTC by AntaOtk

верстка 3х экранов

2024-04-09 19:36 UTC, Bivis63 requested changes

2024-04-09 19:36 UTC, Bivis63 commented on app/src/main/java/com/innoprog/android/feature/auth/codeentry/presentation/CodeEntryFragment.kt
> +        email = arguments?.getString("Arg")
Давай вынесем Arg в константу ?

2024-04-10 17:38 UTC, Bivis63 commented
detekt не прошёл , поправь плиз и сольём :)

2024-04-10 18:42 UTC, AntaOtk commented
Push  не прошел🙈

2024-04-11 17:05 UTC, Bivis63 approved these changes

2024-04-11 17:05 UTC, Bivis63 commented on app/src/main/java/com/innoprog/android/feature/auth/codeentry/presentation/CodeEntryViewModel.kt
> +        const val DURATION = 15000L
Лучше указывать наименования единиц для констант. Например DURATION_MILLIS

2024-04-11 17:06 UTC, merged