71 52 additional information
InnoProg-Project/my_startup pull request #131
Opened 2024-04-16 17:27 UTC by NadezhdaSakal

2024-04-18 06:23 UTC, n-shvedov27 requested changes

2024-04-18 06:23 UTC, n-shvedov27 commented on uikit/src/main/res/layout/inno_prog_input_view.xml
> +            android:singleLine="false"
Кажется это нужно вынести в параметры всего InnoProgInputView и настраивать уже в месте использования, потому что не везде он должен быть multiline

2024-04-19 17:09 UTC, Bivis63 approved these changes

2024-04-23 09:04 UTC, BigMag74 approved these changes

2024-04-24 06:29 UTC, n-shvedov27 approved these changes

2024-04-24 06:29 UTC, merged