65 image upload fragment
InnoProg-Project/my_startup pull request #132
Opened 2024-04-16 20:37 UTC by BigMag74

2024-04-18 06:02 UTC, n-shvedov27 requested changes

2024-04-18 06:02 UTC, n-shvedov27 commented on app/src/main/res/drawable/ic_add_image.xml
А почему иконки не в uikit?

2024-04-18 06:02 UTC, n-shvedov27 commented on app/src/main/res/drawable/ic_delete_2.xml
Почему ic_delete_2?

2024-04-18 06:02 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_upload_image_and_video.xml
> +        <com.innoprog.android.uikit.InnoProgTopBarView
А этому фрамгенту точно нужен topBar?
Он же будет встраиваться в родительский фрагмент с другим тапБаром

2024-04-22 10:59 UTC, BigMag74 commented on app/src/main/res/drawable/ic_delete_2.xml
У нас уже есть ic_delete и delete_photo, не знал как примерно такое же изображение назвать

2024-04-22 17:18 UTC, NadezhdaSakal approved these changes

2024-04-24 11:40 UTC, Bivis63 commented
![tools](https://github.com/InnoProg-Project/InnoProg/assets/112636181/56bee346-de84-4bb5-bc12-bbcddab9f194)
в тексте на кнопках стоят tools

2024-04-24 12:17 UTC, Bivis63 approved these changes

2024-04-25 05:24 UTC, n-shvedov27 approved these changes

2024-04-25 05:24 UTC, n-shvedov27 commented
Как билд пройдет можно сливать

2024-04-25 21:58 UTC, merged