52-сделал экран "О проекте "
InnoProg-Project/my_startup pull request #135
Opened 2024-04-17 20:26 UTC by Bivis63

2024-04-18 06:04 UTC, n-shvedov27 requested changes
К какой задаче относится этот пр?
У ветки префикс 52-... 
#52  - это эпик

2024-04-18 06:11 UTC, n-shvedov27 requested changes

2024-04-18 06:11 UTC, n-shvedov27 commented on app/src/main/res/navigation/app_nav_graph.xml
> +    <fragment
Можем добавить какую-нибудь кнопкочку, для открытия этого нового фрагмента?

2024-04-18 06:11 UTC, n-shvedov27 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Это точно нужно?

2024-04-19 17:08 UTC, Bivis63 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
удалил , название поменял, как я так ошибся ))

2024-04-23 08:57 UTC, TanyaRul commented on app/src/main/res/layout/fragment_project_details.xml
> +                android:id="@+id/tv_doc_dox"
Здесь нет опечатки? И стиль именования элемента отличается от остальных

2024-04-23 09:14 UTC, TanyaRul approved these changes

2024-04-23 09:30 UTC, BigMag74 requested changes

2024-04-23 09:30 UTC, BigMag74 commented on app/src/main/res/values/projects_string.xml
> +    <string name="descriptions">Описание(необязательно)</string>
тут пробел забыл

2024-04-23 09:32 UTC, BigMag74 commented on app/src/main/res/layout/fragment_project_details.xml
> +                    android:id="@+id/logoImageView"
Здесь отступ сверху нужен
![image](https://github.com/InnoProg-Project/InnoProg/assets/116560396/c12198f1-5b71-4702-9987-5ac289ab14cd)
![image](https://github.com/InnoProg-Project/InnoProg/assets/116560396/e7fa988f-aff6-4e36-9f12-f29e3fab3aeb)

2024-04-23 10:46 UTC, Bivis63 commented on app/src/main/res/layout/fragment_project_details.xml
> +                    android:id="@+id/logoImageView"
добавил отступ )

2024-04-23 10:47 UTC, Bivis63 commented on app/src/main/res/layout/fragment_project_details.xml
> +                android:id="@+id/tv_doc_dox"
Действительно! ) Поправил )

2024-04-24 11:17 UTC, BigMag74 commented on app/src/main/res/layout/fragment_project_details.xml
> +                    android:visibility="visible"/>
а это зачем? 
![image](https://github.com/InnoProg-Project/InnoProg/assets/116560396/953f126d-00d7-4d35-96b2-871c57ebbe78)

2024-04-24 14:37 UTC, TanyaRul commented on app/src/main/res/layout/fragment_project_details.xml
> +            android:id="@+id/tvHeadLine"
Нужно указать цвет текста, сейчас отличается от макета

2024-04-24 14:38 UTC, TanyaRul commented on app/src/main/res/layout/fragment_project_details.xml
> +                style="@style/TextSubtitle_1"
Тоже нужно цвет текста указать

2024-04-24 14:48 UTC, TanyaRul commented on app/src/main/res/layout/fragment_project_details.xml
> +            android:id="@+id/btСontinue"
Кажется, у всех наших кнопок что-то не то со скруглением углов
![capture](https://github.com/InnoProg-Project/InnoProg/assets/118722638/f89baf4f-381d-4cc6-b178-741f5ae6c832)

2024-04-26 09:22 UTC, Bivis63 commented on app/src/main/res/layout/fragment_project_details.xml
> +                    android:visibility="visible"/>
Проверял отступ

2024-04-26 09:24 UTC, Bivis63 commented on app/src/main/res/layout/fragment_project_details.xml
> +            android:id="@+id/tvHeadLine"
Поставил text_primary

2024-04-26 09:25 UTC, Bivis63 commented on app/src/main/res/layout/fragment_project_details.xml
> +                style="@style/TextSubtitle_1"
тут тоже поправил

2024-04-26 09:30 UTC, Bivis63 commented on app/src/main/res/layout/fragment_project_details.xml
> +            android:id="@+id/btСontinue"
Если у нас проблема со всеми кнопками , предлагаю вынести это в отдельную задачу

2024-04-26 12:09 UTC, BigMag74 approved these changes

2024-04-26 19:34 UTC, TanyaRul approved these changes

2024-04-27 05:26 UTC, n-shvedov27 approved these changes

2024-04-28 17:24 UTC, merged