[#31] Привязка экрана логина к api
InnoProg-Project/my_startup pull request #164
Opened 2024-04-23 21:53 UTC by AntaOtk

логика обработки немного не доделана, в остальном вроде работает

2024-05-02 06:35 UTC, n-shvedov27 requested changes
Нужны два лайка

2024-05-02 14:59 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/AuthorisationRepositoryImpl.kt
> +            }
можно вынести в ресурсы или  унести в констаны API

2024-05-02 15:02 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/AuthorisationRepositoryImpl.kt
сейчас не  проходит детект из-за мелкх недочетов типа пробела или длинной строки (можно посмотреть в деталях детекта тут)

2024-05-02 15:03 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/RetrofitNetworkClient.kt
> +    private fun isConnected(): Boolean {
чтобы детект пропускал этот метод я слазила в конфиг)

2024-05-02 15:06 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/presentation/AuthorizationFragment.kt
> +    private fun customizeIV(){
тут не хватает пробела

2024-05-02 15:08 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/presentation/AuthorizationViewModel.kt
> +class AuthorizationViewModel @Inject constructor(private val useCase: AuthorisationUseCase, private val context: Context) :
тут

2024-05-02 15:31 UTC, AntaOtk commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/RetrofitNetworkClient.kt
> +    private fun isConnected(): Boolean {
сомнительно, но OK. думаю нам нужно мнение Никиты на этот счет

2024-05-03 05:40 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/RetrofitNetworkClient.kt
> +    private fun isConnected(): Boolean {
По возможности конфиг не меняем
Кажется тут можно заменить на что-то [типо](https://pastebin.com/rFdj7xZH)

2024-05-06 15:14 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/RetrofitNetworkClient.kt
> +    private fun isConnected(): Boolean {
сделала этот метод, не меняя настроек детекта, можно посмотреть в моем ПРе

2024-05-09 06:41 UTC, NadezhdaSakal approved these changes

2024-05-10 08:33 UTC, AndrewkaW approved these changes

2024-05-13 06:30 UTC, n-shvedov27 requested changes

2024-05-13 06:30 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/AuthSharedPReferencesLocalStorage.kt
> +class AuthSharedPReferencesLocalStorage @Inject constructor(
AuthSharedPreferencesLocalStorage

2024-05-13 06:30 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/AuthSharedPReferencesLocalStorage.kt
> +class AuthSharedPReferencesLocalStorage @Inject constructor(
Да хотя лучше наверное AuthLocalStorageImpl

2024-05-13 06:30 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/AuthorisationRepositoryImpl.kt
> +    private val sharedPreferences: AuthSharedPReferencesLocalStorage,
Зачем тогда интерфейс AuthLocalStorage, если инжектится реализация?

2024-05-13 06:30 UTC, n-shvedov27 commented on gradle/wrapper/gradle-wrapper.properties
> -distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip
Для чего эти изменения?

2024-05-13 06:30 UTC, n-shvedov27 commented on build.gradle.kts
> +    id("com.android.application") version "8.3.2" apply false
И эти

2024-05-13 13:42 UTC, AntaOtk commented on build.gradle.kts
> +    id("com.android.application") version "8.3.2" apply false
нечаянно, вернула

2024-05-14 07:14 UTC, n-shvedov27 requested changes

2024-05-14 07:14 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/AuthorisationRepositoryImpl.kt
> +    override fun verify(login: String, password: String): Flow<Resource<UserData>> = flow {
Для чего тут используется flow?
Почему просто метод suspend  не сделать?

2024-05-14 07:14 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/network/AuthorizationBody.kt
> +    val username: String,
@SerializationName

2024-05-14 07:14 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/network/RetrofitNetworkClient.kt
> +                val response = api.authorize(dto)
Как будто можно было вызов api оставить в repository
И RetrofitNetworkClient првератить просто в маппер из LoginResponse в UserData

2024-06-13 17:58 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/presentation/AuthorizationViewModel.kt
> +            }
По умолчанию viewModelScope.launch выполняется на main потоке + при отсутствии интернета мне возвращает другие исключение, которое не обрабатывается в repository и происходит crush. Поэтому лучше дополнительно обрабатывать исключения в viewModel.
```kotlin
viewModelScope.launch(Dispatchers.IO) {
    runCatching {
        // run UseCase
    }.onFailure { exception ->
        // handle error
    }
}

2024-06-13 17:58 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/AuthorisationRepositoryImpl.kt
> +            Log.d("1234", response.code().toString())
1. Тут лучше сохранить значение header в AuthHeader, хорошо бы сделать сохранение через дополнительную абстракцию (useCase + repository), чтобы потом можно было подменить сохранение и доставание данных для авторизации.  
2. Лучше сделать прокидывание заголовка @Header("X-Authorization") через interceptors. Это позволит не писать логику по добавлению header для каждого запроса. Добавить interceptor необходимо в NetworkModule в методе provideOkHttpClient() примерно следующим образом:
```kotlin
@Provides
    fun provideOkHttpClient(
        getAuthorizationDataUseCase: GetAuthorizationDataUseCase
    ): OkHttpClient {
        return OkHttpClient.Builder()
            .callTimeout(ApiConstants.CALL_TIMEOUT.toLong(), TimeUnit.SECONDS)
            .readTimeout(ApiConstants.READ_TIMEOUT.toLong(), TimeUnit.SECONDS)
            .addInterceptor(HttpLoggingInterceptor().apply {
                level = HttpLoggingInterceptor.Level.BODY
            })
            .addInterceptor { chain ->
                chain.run {
                    proceed(
                        request()
                            .newBuilder()
                            .addHeader("X-Authorization", getAuthorizationDataUseCase.execute())
                            .build()
                    )
                }
            }
            .build()
    }
```
GetAuthorizationDataUseCase будет использовать repository для получения данных, который мы создали на шаге 1.

2024-06-13 17:58 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/data/network/LoginApi.kt
> +        @Header("X-Authorization") header: String
Если сделать через interceptors как писал выше, то тут уже header не нужен

2024-06-14 15:23 UTC, Secur1ty-21 approved these changes
Все работает корректно, на других экранах теперь тоже приходят положительные ответы, молодец!

2024-06-14 15:23 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/domain/AuthorisationUseCaseImpl.kt
> +        val header = "Basic " + Base64.getEncoder().encodeToString(authData.toByteArray())
Лучше вынести эту логику в AuthorizationDataRepository

2024-06-14 15:23 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/network/data/NetworkModule.kt
> +        authorizationDataRepository: AuthorizationDataRepositoryImpl
Лучше абстракцию а не имплементацию : AuthorizationDataRepository

2024-06-17 14:34 UTC, merged