125 41 привязка экрана профиля к api
InnoProg-Project/my_startup pull request #165
Opened 2024-04-28 12:24 UTC by NadezhdaSakal

2024-05-02 06:35 UTC, n-shvedov27 requested changes
Нужны два лайка

2024-05-02 15:18 UTC, AntaOtk approved these changes

2024-05-02 15:18 UTC, AntaOtk commented on app/src/main/java/com/innoprog/android/feature/profile/profiledetails/data/network/RetrofitNetworkClient.kt
> +    private fun isConnected(): Boolean {
у меня на много возвратов detect ругается

2024-05-02 15:18 UTC, AntaOtk commented on app/src/main/java/com/innoprog/android/di/AppComponent.kt
> +
выглядит единственным изменением. лучше так не делать. может лишние конфликты породить, если кто-то правит этот файл.

2024-05-03 05:42 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/profile/profiledetails/data/network/RetrofitNetworkClient.kt
> +    private fun isConnected(): Boolean {
Приложу [ссылку](https://github.com/InnoProg-Project/InnoProg/pull/164#discussion_r1588760601) на обсуждение на всякий

2024-05-03 17:17 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/feature/profile/profiledetails/data/network/RetrofitNetworkClient.kt
> +    private fun isConnected(): Boolean {
исправила, не меняя detekt

2024-05-03 18:55 UTC, BigMag74 commented on app/src/main/java/com/innoprog/android/feature/profile/profiledetails/presentation/ProfileViewModel.kt
> +            _uiState.value = ProfileScreenState.Error(ErrorType.NOT_FOUND)
Вот это я не совсем понял зачем нужно

2024-05-03 18:57 UTC, BigMag74 commented on app/src/main/java/com/innoprog/android/base/BaseViewModel.kt
> +            launchBody.invoke()
Функция нигде в итоге не использовалась

2024-05-03 21:32 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/base/BaseViewModel.kt
> +            launchBody.invoke()
исправила

2024-05-03 21:35 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/feature/profile/profiledetails/presentation/ProfileViewModel.kt
> +            _uiState.value = ProfileScreenState.Error(ErrorType.NOT_FOUND)
вообще подумала, что надо бы обработать ошибку, если пошло что-то не так, хотя у нас по макету и нет такого, в дальнейшем можно будет прикрутить сюда бд, чтоб брать данные из нее

2024-05-04 08:21 UTC, BigMag74 approved these changes

2024-05-06 06:38 UTC, n-shvedov27 requested changes

2024-05-06 06:38 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/network/data/ApiService.kt
> +    suspend fun loadProfileCompany(): ProfileCompanyResponse
А зачем тебе новые методы, если у тебя уже есть post и get?
В принципе можно отойти от идеи общего ApiService и под каждую фичу делать свой 
Пример есть в [тут](https://github.com/n-shvedov27/AppExample)

2024-05-06 06:40 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/network/data/ApiService.kt
> +    suspend fun loadProfileCompany(): ProfileCompanyResponse
<img width="689" alt="Снимок экрана 2024-05-06 в 11 40 39" src="https://github.com/InnoProg-Project/InnoProg/assets/37715977/895dbe48-e9a5-4133-bd2e-e70c80cd0929">

2024-05-08 05:40 UTC, n-shvedov27 approved these changes

2024-05-08 05:40 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/profile/profiledetails/data/network/ProfileResponse.kt
> +    val userId: String,
Лучше прописывать название полей через аннотацию @SerializationName
Тк при обфускации сборки названия этих переменных поменяются

2024-05-13 06:01 UTC, merged