add api to registration
InnoProg-Project/my_startup pull request #171
Opened 2024-05-22 18:14 UTC by AntaOtk

не разобралась с обработкой полученных данных

2024-05-24 22:48 UTC, Secur1ty-21 requested changes
В api на регистрацию есть поля about и languge, не совсем понятно зачем они нужны, думаю стоит уточнить у заказчика. Еще желательно поле пароля сделать таким, чтобы пароль не показывался, но была возможность показать, нажав на глазик

2024-05-24 22:48 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/data/RegistrationBody.kt
> +    val language: String?
Рекомендую добавить над каждым полем SerializedName(""), при обфускации кода с proguard имена полей меняются, и GsonConverter неправильно конвернет класс в json

2024-05-24 22:48 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/data/RegistrationRepositoryImpl.kt
> +                }
В api success code при регистрации = 201, поэтому при успешной регистрации показывает в тосте error. Советую для каждого запроса составлять свой enum кодов ответов

2024-05-24 22:48 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/data/RegistrationRepositoryImpl.kt
>          }
При отсутствии интернета возникает исключение SocketTimeoutException, catch блок его не ловит и приложение вылетает, советую добавить обработку этого исключения и в зависимости от типа кода ошибки и исключения показывать соответствующие сообщения пользователю

2024-05-24 22:48 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/data/RegistrationResponse.kt
> +data class RegistrationResponse(
Думаю именно data class тут необязательно использовать, можно просто class

2024-05-24 22:48 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/domain/RegistrationUseCaseImpl.kt
> +                (data.password?.length ?: ZERO) in MIN_PASSWORD..MAX_PASSWORD
Думаю лучше эти проверки делать из viewModel и на каждую ошибку выводить свое информационное сообщение

2024-05-24 22:48 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/presentation/RegistrationViewModel.kt
> +                            context, R.string.registration_toast_message
Думаю лучше context не прокидывать во viewModel, может вызвать утечки памяти

2024-05-24 22:48 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/presentation/RegistrationViewModel.kt
>                  }
Необходимо делать запрос с IO потоков, по умолчанию viewModelScope работает на Main + желательно всю логику работы useCase дополнительно оборачивать в runCatching
```kotlin
viewModelScope.launch(Dispathers.IO) {
    runCatching {
        // useCase
    }.onFailure { exception ->
        // обработка исключений
    }
}

2024-06-05 15:45 UTC, Secur1ty-21 requested changes
Еще заметил баг с edit text, при пересоздании activity ( поворот экрана, смена языка, масштабирование размера шрифта ), введенное значение в последний edit text прописывается во все остальные. Это не только на экране регистрации, поэтому думаю заведем отдельную таску на исправление этого бага

2024-06-05 15:45 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/auth/registration/data/RegistrationRepositoryImpl.kt
> +                }
Retrofit самостоятельно не прописывает resultCode в ответ, необходимо сделать это вручную
1. Обернуть ответ в Response
```kotlin
@POST("/v1/registration")
    suspend fun setRegistrationData(@Body body: RegistrationBody): Response<RegistrationResponse>
```
Теперь в Repository в качестве ответа будет приходить Response<RegistrationResponse>
```kotlin
val response = api.setRegistrationData(mapToRegistrationRequest(registrationValue))
Log.v("123", "result code = ${response.code()}")
when (response.code()) {
    BAD_REQUEST_CODE -> {
        emit(Pair(false, "error"))
    }

    SUCCESS_CODE -> {
        Pair(true, null)
    }

    else -> {
        emit(Pair(false, "error"))
    }
}
```

2024-06-07 20:17 UTC, Secur1ty-21 approved these changes

2024-06-08 06:26 UTC, TanyaRul approved these changes

2024-06-10 15:30 UTC, merged