48 Экран чужого проекта
InnoProg-Project/my_startup pull request #172
Opened 2024-05-24 09:01 UTC by TanyaRul

2024-05-24 17:23 UTC, Secur1ty-21 requested changes
Если замокать 100 публикаций и перейти на этот экран то приложение виснет (ANR), необходимо оптимизировать верстку. Параметры моего устройства: Android 14, 8 + 256, Snapdragon 695.

2024-05-24 17:23 UTC, Secur1ty-21 commented on app/src/main/res/layout/fragment_any_project.xml
> +                android:padding="@dimen/padding_16"
Не соответствует дизайну, у title отступ от верха карточки 12dp

2024-05-24 17:23 UTC, Secur1ty-21 commented on app/src/main/res/layout/fragment_any_project.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Можно заменить на более легковесный LinearLayout

2024-05-24 17:23 UTC, Secur1ty-21 commented on app/src/main/res/layout/fragment_any_project.xml
> +                app:layout_constraintGuide_end="@dimen/margin_8" />
Можно заменить на LinearLayout + paddingHorizontal="8dp"

2024-05-24 17:23 UTC, Secur1ty-21 commented on app/src/main/res/layout/fragment_any_project.xml
> +                android:visibility="visible"
По умолчанию вроде visible

2024-05-24 17:23 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/presentation/AnyProjectViewModel.kt
> +        }
Думаю стоит добавить Dispatchers.IO и обернуть вызов useCase в runCatching
```kotlin
viewModelScope.launch(Dispatchers.IO) {
            runCatching {
                   // Вызов useCase
            }.onFailure { exception ->
                  // Обработка исключений, если вдруг такие возникли
            }
}
```

2024-05-24 17:23 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/presentation/AnyProjectScreenState.kt
> +    data class Content(val anyProject: AnyProjectModel) : AnyProjectScreenState
Думаю именно data class тут необязательно, можно просто class

2024-05-24 17:23 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/presentation/AnyProjectFragment.kt
> +    private var newsAdapter: NewsAdapter? = null
Думаю лучше инициализировать сразу, чтобы не был nullable

2024-05-24 17:23 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/presentation/AnyProjectFragment.kt
Думаю для ленты публикаций тоже лучше сразу сделать репозитория и usecase для Мока

2024-05-24 17:23 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/domain/AnyProjectModel.kt
Над каждым полем лучше добавить аннотацию, если сделать обфускацию через proguard, то имена полей будут изменены на рандомные и gson не сможет раскрасить ответ и положить в этот класс.
```kotlin
 @SerializedName("id")
val id: String,
 @SerializedName("name")
val name: String,
```

2024-05-28 12:44 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/domain/AnyProjectModel.kt
Поняла. А есть ещё вариант использовать Parcelable, что лучше?

2024-05-28 13:10 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/domain/AnyProjectModel.kt
Варианта Parcelable нету, он для сериализации и десериализации, ты наверное перепутала SerializedName с Serializable.

Вот что делает SerializedName 
https://stackoverflow.com/questions/28957285/what-is-the-basic-purpose-of-serializedname-annotation-in-android-using-gson

2024-05-28 13:47 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/domain/AnyProjectModel.kt
Упс, точно

2024-06-03 07:52 UTC, TanyaRul commented on app/src/main/res/layout/fragment_any_project.xml
> +                android:padding="@dimen/padding_16"
Исправила

2024-06-03 07:52 UTC, TanyaRul commented on app/src/main/res/layout/fragment_any_project.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Изменила

2024-06-03 07:52 UTC, TanyaRul commented on app/src/main/res/layout/fragment_any_project.xml
> +                app:layout_constraintGuide_end="@dimen/margin_8" />
Изменила

2024-06-03 07:52 UTC, TanyaRul commented on app/src/main/res/layout/fragment_any_project.xml
> +                android:visibility="visible"
Исправила

2024-06-03 07:53 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/presentation/AnyProjectViewModel.kt
> +        }
Добавила

2024-06-03 07:53 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/presentation/AnyProjectScreenState.kt
> +    data class Content(val anyProject: AnyProjectModel) : AnyProjectScreenState
Изменила

2024-06-03 07:53 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/presentation/AnyProjectFragment.kt
> +    private var newsAdapter: NewsAdapter? = null
Изменила

2024-06-03 07:53 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/feature/feed/projectScreen/presentation/AnyProjectFragment.kt
Добавила

2024-06-03 16:57 UTC, Secur1ty-21 approved these changes

2024-06-04 04:10 UTC, NadezhdaSakal approved these changes

2024-06-08 06:25 UTC, merged