180 bind api get projects
InnoProg-Project/my_startup pull request #188
Opened 2024-06-25 21:38 UTC by GoetzDeBouville

Провайдит сеть в [экран списка проектов профиля](https://www.figma.com/design/tNhKnPzlgQNt0VpI2zODzi/%D0%A1%D1%82%D0%B0%D1%80%D1%82%D0%B0%D0%BF?node-id=3826-2902&t=sTlK4ni5k8oACVMM-4)
Добавляет общие классы для обработки ошибок
корректирует модели
корректирует фрагмент и адаптер

2024-07-01 21:08 UTC, AndrewkaW approved these changes

2024-07-02 14:16 UTC, NadezhdaSakal approved these changes

2024-07-02 23:40 UTC, Secur1ty-21 requested changes

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/data/network/ProjectListNetworkClientImpl.kt
> +        }
Сейчас возвращает 400 Bad Request, после того как убрал параметры пагинации возвращало 200, возможно проблема на стороне бэка, при этом ошибку не показывает т.к. при любом ответе присваивается SUCCESS_CODE

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/data/dto/ProjectDto.kt
Лучше проставлять у сетевых моделек, которые будут создаваться через GsonConverter, аннотацию SerializedName(). Это нужно чтобы GsonConverter мог работать дальше после затирания имен полей обфускацией

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/data/converter/ProjectConverter.kt
> +fun ProjectDto.convert() = Project(
К данному проекту не применимо, но лучше давать более явные названия методам конвертации . Очень часто в больших проектах кроме Domain модели есть еще ui модель.

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/data/repository/ProjectRepositoryImpl.kt
> +        const val ERROR_TAG = "ProjectRepository"
Лучше не хардкодить теги, имена классов могут изменить, а про тег забыть, часто замечаю в легаси эти несостыковки 
```kotlin
val ERROR_TAG = ProjectRepository::class.simpleName
```

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/data/network/ProjectListNetworkClientImpl.kt
> +) : ProjectListNetworkClient {
Лучше сделать провайд именно profileDao, чтобы не было доступа к сущностям которые не используются в этом классе

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/di/ProjectsFragmentModule.kt
> +    fun bundRepository(impl: ProjectRepositoryImpl): ProjectRepository
Опечатки в именах

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/domain/impl/GetProjectListUseCaseImpl.kt
> +                Resource.Success(projects)
domain слой не должен знать о data, тут это правило нарушается т.к. используется моделька Data слоя

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/profile/profiledetails/data/db/ProfileDao.kt
>  }
Добавлю задачку по очистке бд при повторной авторизации под другим акком, пока что поведение может быть неправильным

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/presentation/adapter/ProjectsScreenAdapter.kt
> +        }
Не применимо к текущим потенциальным размерам списка, но лучше сразу вешать clickListener в onCreateViewHolder, чтобы делать это только один раз при создании

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/presentation/ProjectsScreenViewModel.kt
>              }
Лучше через следующую структуру
```kotlin
viewModelScope.launch(Dispatchers.IO) { // По умолчанию viewModelScope запускается на Main потоке
    runCatching {
      // run useCase
    }.onFailure {
        // Дополнительно обрабатываем ошибки, например они могли возникнуть при маппинге модели в useCase или если другие разработчики что то сломают
    }
}
```

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/presentation/ProjectsScreenFragment.kt
> +            viewModel.navigateTo(direction)
Думаю тут лучше использовать findNavController.popBackStack с параметрами 
```kotlin
        findNavController().popBackStack(destinationId = R.id.some_id, inclusive = true)
```

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/presentation/ProjectsScreenState.kt
> +    data class Content(val projects: List<Project>) : ProjectsScreenState
Именно Data class тут необязательно, он генерит доп методы которые мы не используем. Большое количество Data классов замедляют сборку релизной версии

2024-07-02 23:40 UTC, Secur1ty-21 commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/presentation/ProjectsScreenViewModel.kt
> +            ErrorType.UNAUTHORIZED -> ProjectsScreenState.Error(ErrorScreenState.SERVER_ERROR)
ErrorScreenState.UNAUTHORIZED

2024-07-05 13:35 UTC, Zedd3d approved these changes

2024-07-05 20:34 UTC, Secur1ty-21 reviewed
Убрал случайно уставленный clickListener в методе bind, добавил обработку потенциально возможных исключений при маппинге модели проекта в Domain ( Например пришли битые данные с сервера )

2024-07-05 20:34 UTC, Secur1ty-21 approved these changes

2024-07-05 20:36 UTC, merged