54 api fragment owner project
InnoProg-Project/my_startup pull request #193
Opened 2024-06-30 14:17 UTC by Zedd3d

[#52] Связка с api экрана своего и чужого проекта
[#54](https://github.com/InnoProg-Project/InnoProg/issues/54)

- Отредактировал навигационный граф, добавил переменную itsCustomProject 
- Добавил переход из пункта меню "Проекты" так же добавив projectId и itsCustomProject
- Добавил класс SingleLiveEvent и функцию debounceFun, таким образом реализовал защиту от двойного нажатия при переходе с экрана новости на экран проекта
- Добавил click debounce при переходе из экрана "Проекты" в "свой" проект
- Реализовал переходы из экрана "Новость" и экрана "Проекты" с контекстами чужой и свой соответственно. При переходе  в свой проект отображается кнопка "Создать публикацию"

2024-07-01 15:28 UTC, TanyaRul approved these changes

2024-07-02 14:13 UTC, GoetzDeBouville requested changes
Оставил комменты, в ветке не учитываются изменения, которые уже введены в ветках 52 и 180

2024-07-02 14:13 UTC, GoetzDeBouville commented on app/src/main/java/com/innoprog/android/util/Debounce.kt
> +fun <T> debounceFun(
Для этого метода стоит дать описание что он делает и за что отвечают его параметры. 
Так же добавить дефолтные значения для delayMillis и useLastParam. Пример этой функции я давал ссылкой на свой гист

2024-07-02 14:13 UTC, GoetzDeBouville commented on app/src/main/res/layout/fragment_any_project.xml
> +        <com.innoprog.android.uikit.InnoProgButtonView
В этом файле я [тоже провел изменения](https://github.com/InnoProg-Project/InnoProg/pull/192), ты был на ревью, стоит все-таки определиться, кто будет проводить корректировки. Думаю что нам как-то не очень удачно расписали задачи по эпику

2024-07-02 14:13 UTC, GoetzDeBouville commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/presentation/ProjectsScreenFragment.kt
Класс ProjectScreenFrafment я корректирую в 180 ПР, влей его в эту ветку, там много что поменялось

2024-07-02 14:13 UTC, GoetzDeBouville commented on app/src/main/java/com/innoprog/android/feature/projects/projectsScreen/presentation/ProjectsScreenFragment.kt
Думаю что логичным будет влить в эту ветку [вот эту](https://github.com/InnoProg-Project/InnoProg/tree/52_project_details_api) ветку, т.к. она уже использует 180 ветку. Соответственно, после слияния веток делать ПР в 54 ветку, а не в develop, пока 54 ветка не будет влита в develop

2024-07-15 09:41 UTC, Secur1ty-21 approved these changes

2024-07-15 09:44 UTC, merged