detekt
InnoProg-Project/my_startup pull request #21
Opened 2024-03-06 13:28 UTC by NadezhdaSakal

Не уверена, что работает

2024-03-06 18:36 UTC, n-shvedov27 requested changes

2024-03-06 18:36 UTC, n-shvedov27 commented on gradle/wrapper/gradle-wrapper.properties
> +#Wed Mar 06 12:38:17 MSK 2024
А зачем тут изменения?

2024-03-06 18:39 UTC, NadezhdaSakal commented on gradle/wrapper/gradle-wrapper.properties
> +#Wed Mar 06 12:38:17 MSK 2024
Оно, наверное, автоматически поменялось

2024-03-07 04:30 UTC, n-shvedov27 requested changes

2024-03-07 04:30 UTC, n-shvedov27 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip
Убери ещё пожалуйста это изменение и сольем)

2024-03-07 04:44 UTC, NadezhdaSakal commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip
окай)

2024-03-07 04:44 UTC, n-shvedov27 approved these changes

2024-03-07 04:44 UTC, merged