8 avatar custom view
InnoProg-Project/my_startup pull request #26
Opened 2024-03-08 09:28 UTC by BigMag74

2024-03-09 07:31 UTC, n-shvedov27 requested changes

2024-03-09 07:31 UTC, n-shvedov27 commented on build.gradle.kts
> +    config.from(files("config/detekt/detekt.yml"))
Для чего это изменение?

2024-03-09 07:31 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/AvatarCustomView.kt
> +inline fun AttributeSet.applyStyleable(
Давай вынесем это в отдельный файл
Например com.innoprog.android.uikit.ext.View

2024-03-09 07:31 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/AvatarCustomView.kt
> +) : ConstraintLayout(context, attrs, defStyleAttr) {
Может быть сразу наследовать от FrameLayout?
Тогда отпала бы потребность в излишней вложенности вьюх и можно было бы убрать avatar_frame_layout

Android'у проще плоские вьюхи отрисовывать

2024-03-09 07:31 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/AvatarCustomView.kt
> +class AvatarCustomView @JvmOverloads constructor(
Переименуй плз в InnoProgAvatarView)
layout и ViewSample тоже

2024-03-10 15:09 UTC, BigMag74 commented on build.gradle.kts
> +    config.from(files("config/detekt/detekt.yml"))
Сам детект ругался на эту строчку, писал что сеттер deprecated и нужно писать через from() или getFrom()

2024-03-10 16:32 UTC, BigMag74 commented on build.gradle.kts
> +    config.from(files("config/detekt/detekt.yml"))
w: file:///home/runner/work/InnoProg/InnoProg/build.gradle.kts:11:5: 'setter for config: ConfigurableFileCollection' is deprecated. Setter will be removed in a future release. Use `from` or `setFrom` instead.

2024-03-11 04:04 UTC, n-shvedov27 requested changes

2024-03-11 04:04 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgAvatarView.kt
> +            frameLayout.background.setTint(color)
А почему вместо этого просто this не использовать?)
Ну и убрать поле frameLayout

2024-03-11 04:04 UTC, n-shvedov27 commented on uikit/src/main/res/layout/innno_prog_avatar_view.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Тут можно было бы использовать
<merge tools:parentTag="..."

2024-03-11 14:49 UTC, n-shvedov27 requested changes

2024-03-11 14:49 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgAvatarView.kt
> +        this@InnoProgAvatarView.background.setTint(context.getColor(R.color.background_secondary))
Подскажи, зачем в обоих ПРах через this@... обращаешься?
Можно же просто `background.setTint(context.getColor(R.color.background_secondary))` написать
Исправь плз и сольем
А то если пропущу потом примером для остальных станет

2024-03-11 14:54 UTC, n-shvedov27 approved these changes

2024-03-11 14:56 UTC, merged