6 custom input view
InnoProg-Project/my_startup pull request #75
Opened 2024-03-13 16:48 UTC by BigMag74

2024-03-14 07:43 UTC, n-shvedov27 commented
Обманул я тебя похоже, не через TextWatcher тут надо бы делать)

Хорошо бы перемещать hint не на изменение текста, а на попадание в фокус
https://github.com/InnoProg-Project/InnoProg/assets/37715977/ac8cc227-7727-42d8-8614-da0f7d7d4247

Как например тут
https://github.com/InnoProg-Project/InnoProg/assets/37715977/7883e475-94c2-42c0-88f6-da242eb98db7

2024-03-14 07:44 UTC, n-shvedov27 requested changes

2024-03-14 07:44 UTC, n-shvedov27 commented on uikit/src/main/res/layout/inno_prog_input_view.xml
> +            android:id="@+id/hint_empty"
А нельзя обойтись здесь одной вьюхой вместо hint_filled и hint_empty, меняя ее размер и расположение?

2024-03-14 07:44 UTC, n-shvedov27 commented on uikit/src/main/res/drawable/rectangle_with_stroke_test.xml
> +<?xml version="1.0" encoding="utf-8"?>
Давай тогда уж назовем inno_prog_input_view_background?

2024-03-14 07:44 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgInputView.kt
> +        const val FOCUSED = 3
Можно добавить эти числа сразу в InnoProgInputViewState
<img width="678" alt="Снимок экрана 2024-03-14 в 12 35 02" src="https://github.com/InnoProg-Project/InnoProg/assets/37715977/7732ad0c-4f8e-49cc-8320-ad95cf9614f6">

2024-03-14 07:44 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgInputView.kt
> +        val imm = context.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
Может лучше `inputManager` ?

2024-03-14 07:44 UTC, n-shvedov27 commented on uikit-sample/src/main/java/com/innoprog/android/uikitsample/InnoProgInputViewFragment.kt
> +        binding.inputViewFocusedEmpty.deleteLeftIcon()
Подскажи, а нам обязательно вызывать deleteLeftIcon() каждый раз, если мы не хотим отображать иконку?

Разве не достаточно будет просто не проставлять ее  в xml?

2024-03-14 15:48 UTC, BigMag74 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgInputView.kt
> +        const val FOCUSED = 3
Я так и делал, но detekt ругался на "magic number" поэтому вынес в константы

2024-03-14 19:12 UTC, n-shvedov27 requested changes

2024-03-14 19:12 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgInputView.kt
> +    private val textWatcher by lazy {
Ты по-моему этот коммент не поправил
https://github.com/InnoProg-Project/InnoProg/pull/75#issuecomment-1996753326

2024-03-14 19:58 UTC, BigMag74 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgInputView.kt
> +    private val textWatcher by lazy {
а да, пропустил его

2024-03-15 06:34 UTC, n-shvedov27 commented
Уже гораздо лучше)
Только теперь высота элемента начала почему-то меняться
https://github.com/InnoProg-Project/InnoProg/assets/37715977/77451c2d-4150-4646-87d2-4bb8726e658e

2024-03-15 06:41 UTC, n-shvedov27 requested changes
Уже гораздо лучше)
Только теперь высота элемента начала почему-то меняться
https://github.com/InnoProg-Project/InnoProg/assets/37715977/77451c2d-4150-4646-87d2-4bb8726e658e

2024-03-15 11:29 UTC, n-shvedov27 approved these changes

2024-03-15 11:29 UTC, merged