сделал CustomChip
InnoProg-Project/my_startup pull request #78
Opened 2024-03-14 10:13 UTC by Bivis63

2024-03-14 13:19 UTC, n-shvedov27 requested changes

2024-03-14 13:19 UTC, n-shvedov27 commented on uikit/src/main/res/layout/inno_prog_chip_view.xml
> +    <com.google.android.material.chip.Chip
Если ты просто используешь com.google.android.material.chip.Chip, то может в этой вьюхе сразу сделаем Selector этих чипов?
Вот для этого [экрана](https://www.figma.com/file/tNhKnPzlgQNt0VpI2zODzi/%D0%A1%D1%82%D0%B0%D1%80%D1%82%D0%B0%D0%BF?type=design&node-id=3805-5367&mode=design&t=Q8PuOwFawk00AYJ7-4)
<img width="463" alt="Снимок экрана 2024-03-14 в 18 15 48" src="https://github.com/InnoProg-Project/InnoProg/assets/37715977/42ff88ec-1859-421a-bbd5-fc22e040933a">

Просто сейчас в этой вьюхе как будто не так много смысла, тк по сути она обертка над гугловским chip'ом

2024-03-16 08:04 UTC, n-shvedov27 requested changes

2024-03-16 08:04 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgChipGroupView.kt
> +                child.setChipBackgroundColorResource(android.R.color.white)
child.setChipBackgroundColorResource(R.color.background_primary)

2024-03-16 08:04 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgChipGroupView.kt
> +                it.setTextColor(ContextCompat.getColor(context, android.R.color.black))
it.setTextColor(ContextCompat.getColor(context, R.color.text_secondary))

2024-03-16 08:04 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgChipGroupView.kt
> +    private fun dpToPx(dp: Int): Int {
Давай этот метод в ViewExt вынесем?

2024-03-16 14:12 UTC, Bivis63 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgChipGroupView.kt
> +                it.setTextColor(ContextCompat.getColor(context, android.R.color.black))
тут text_primary  вроде :)

2024-03-16 19:26 UTC, n-shvedov27 approved these changes

2024-03-16 19:26 UTC, merged