5 Create castom view -  InnoProgButtonView
InnoProg-Project/my_startup pull request #82
Opened 2024-03-18 14:53 UTC by AndrewkaW

2024-03-19 17:28 UTC, n-shvedov27 requested changes

2024-03-19 17:28 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgButtonView.kt
> +    private fun setType() {
Давай лучше сделаем `setType()` публичным и добавим в него параметр type
И будем вызывать в методе init

Таким образом мы сможем извне настраивать type и не нужно будет поле хранить

2024-03-19 17:28 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgButtonView.kt
> +        when (size) {
Тут то же самое что и с `setType()`

2024-03-19 17:28 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgButtonView.kt
> +    private fun setIcons() {
Как будто этому методу больше подходит название `updateIconSize()`

2024-03-19 17:28 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgButtonView.kt
> +    private fun setIcons() {
Ну и тут то же самое что и с `setType()`

2024-03-19 20:55 UTC, AndrewkaW commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgButtonView.kt
> +    private fun setIcons() {
там уже есть два публичных метода метода для установки левой и правой картинки

> Ну и тут то же самое, что и с`setType()`

@n-shvedov27

2024-03-20 05:51 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgButtonView.kt
> +    private fun setIcons() {
Хм, публичным можно не делать
Но параметр я бы добавил
Посмотри например InnoProgInputView

2024-03-20 13:31 UTC, n-shvedov27 approved these changes

2024-03-20 13:32 UTC, n-shvedov27 requested changes

2024-03-20 13:32 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgButtonView.kt
> +    private var state =
А нам нужны вообще эти поля?

2024-03-20 20:42 UTC, AndrewkaW commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgButtonView.kt
> +    private var state =
@n-shvedov27 если убрать их то продеться добавлять параметры для функций stateIsEnabled(isEnabled: Boolean) и
setType(type: ButtonType)

2024-03-21 04:26 UTC, n-shvedov27 approved these changes

2024-03-21 04:26 UTC, merged