30 dagger2
InnoProg-Project/my_startup pull request #83
Opened 2024-03-18 19:11 UTC by Bivis63

2024-03-18 19:54 UTC, Bivis63 commented on app/src/main/java/com/innoprog/android/di/AppComponent.kt
> +    @Component.Builder
что лучше использовать Component.Factory или Builder?

2024-03-19 05:36 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/di/AppComponent.kt
> +    @Component.Builder
Тут скорее от потребности исходить надо
Ты инициализируешь компонент либо с помощью фабрики, либо с помощью билдера
Я чаще билдер использую)

2024-03-19 05:43 UTC, n-shvedov27 requested changes

2024-03-19 05:43 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/base/MainFragment.kt
> +
Нам бы по хорошему эту логику вынести в BaseFragment
Вот [пример](https://pastebin.com/wzdw2CAq) того как это можно было бы сделать

2024-03-19 05:43 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/base/MainFragment.kt
> +
Ну и примерно так будет выглядеть наследник

<img width="833" alt="Снимок экрана 2024-03-19 в 10 41 16" src="https://github.com/InnoProg-Project/InnoProg/assets/37715977/e32d0ba4-5de7-4582-9aad-fd61b733724d">

2024-03-19 05:43 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/base/MainFragment.kt
> +        DaggerAppComponent.builder().build().apply {
Под каждый фрагмент надо добавить свой компонент

2024-03-19 05:43 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/base/ViewModelSample.kt
> +class ViewModelSample @Inject constructor() : BaseViewModel()
Под каждый фрагмент надо добавить свою viewModel
ViewModelSample была добавлена просто для примера

2024-03-19 17:36 UTC, n-shvedov27 requested changes

2024-03-19 17:36 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/base/MainFragment.kt
> +        diComponent().inject(this@MainFragment)
Этот инжект не нужен же теперь

2024-03-19 17:36 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/di/AppComponent.kt
> +    fun inject(fragment: PasswordRecoveryFragment)
Все эти методы inject можно удалить

2024-03-19 17:36 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/presentation/viewmodel/CodeEntryViewModel.kt
> +class CodeEntryViewModel @Inject constructor() : BaseViewModel()
Давай лучше группировать fragment'ы и viewModel'и по фичам

Типо 
com.innoprog.android.feature.auth.codeentry.presentation.CodeEntryViewModel
com.innoprog.android.feature.auth.codeentry.presentation.CodeEntryFragment
com.innoprog.android.feature.auth.codeentry.di.CodeEntryComponent

2024-03-19 17:36 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/presentation/fragment/RegistrationFragment.kt
> +    override fun diComponent(): AppComponent = DaggerAppComponent.builder().build()
Под каждый фрамгмент обычно заводится отдельный компонент

2024-03-19 17:37 UTC, n-shvedov27 requested changes

2024-03-19 17:37 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/base/ViewModelSample.kt
> +class ViewModelSample @Inject constructor() : BaseViewModel()
Ее кстати можно теперь вообще удалить

2024-03-21 04:30 UTC, n-shvedov27 approved these changes

2024-03-21 04:31 UTC, merged