7   Create castom view - innoprogsmscodeview
InnoProg-Project/my_startup pull request #84
Opened 2024-03-20 08:44 UTC by AntaOtk

запуталась с тем как сделать Caption.. менять на framelayout  или возможно с liner layout  🤔
в остальном раюотает

2024-03-20 13:37 UTC, n-shvedov27 commented
https://github.com/InnoProg-Project/InnoProg/assets/37715977/5cca7190-e317-4f91-8b81-2da9857f4b67

Нужна возможность удаления символа

2024-03-20 13:39 UTC, n-shvedov27 commented
Еще в примере который я кидал там открывается клавиатура только с цифрами
Нам бы также настроить

2024-03-20 13:45 UTC, n-shvedov27 requested changes

2024-03-20 13:45 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/AndroidExtensions.kt
> +internal fun View.showKeyboard() {
По-моему уже все файл ViewExt
Можно это туда вынести

2024-03-20 13:45 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/SmsCodeSymbolView.kt
> +internal class SmsCodeSymbolView(context: Context, private val symbolStyle: SymbolStyle) :
Прокидывать параметры во вью через конструктор - неоч хорошая практика
Добавишь такую вью в xml версту - получишь краш

2024-03-20 13:45 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/SmsCodeSymbolView.kt
> +        setMeasuredDimension(w, h)
Для чего это?

2024-03-20 13:46 UTC, n-shvedov27 commented
Билд упал
<img width="686" alt="Снимок экрана 2024-03-20 в 18 46 02" src="https://github.com/InnoProg-Project/InnoProg/assets/37715977/454b7876-e267-4c73-bfb4-fe48da96c95e">

2024-03-21 19:42 UTC, AntaOtk commented on uikit/src/main/java/com/innoprog/android/uikit/SmsCodeSymbolView.kt
> +        setMeasuredDimension(w, h)
определение размеров вью... не надо?

2024-03-21 19:45 UTC, AntaOtk commented on uikit/src/main/java/com/innoprog/android/uikit/SmsCodeSymbolView.kt
> +internal class SmsCodeSymbolView(context: Context, private val symbolStyle: SymbolStyle) :
это же вроде вью которого нет самого по себе.... я пока запуталась с тем как по-другому передать...

2024-03-22 03:56 UTC, n-shvedov27 approved these changes

2024-03-22 04:00 UTC, n-shvedov27 commented
Ну и билд все также лежит)

2024-03-22 04:00 UTC, n-shvedov27 requested changes

2024-03-22 04:01 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/SmsCodeSymbolView.kt
> +internal class SmsCodeSymbolView(context: Context, private val symbolStyle: SymbolStyle) :
А можно просто добавить метод, обновляющий `symbolStyle`?

2024-03-22 04:01 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/SmsCodeSymbolView.kt
> +        setMeasuredDimension(w, h)
А какого эффекта этим ты хочешь добиться?
Просто match_parent/wrap_content не хватает?

2024-03-22 04:02 UTC, n-shvedov27 requested changes
Ну и билд все также лежит)

2024-03-22 05:40 UTC, AntaOtk commented on uikit/src/main/java/com/innoprog/android/uikit/SmsCodeSymbolView.kt
> +        setMeasuredDimension(w, h)
если мы не указываем размеры xml, то размер ячейки будет статичен 48dp

2024-03-24 12:39 UTC, n-shvedov27 approved these changes

2024-03-24 12:40 UTC, merged