79 retrofit
InnoProg-Project/my_startup pull request #86
Opened 2024-03-21 17:26 UTC by NadezhdaSakal

2024-03-22 04:17 UTC, n-shvedov27 requested changes

2024-03-22 04:17 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/data/network/ApiConstants.kt
Давай лучше переместим классы связанные с ретрофитом в 
app/src/main/java/com/innoprog/android/network/...

2024-03-22 04:17 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/profile/di/ProfileComponent.kt
> +    modules = [ProfileModule::class, NetworkModule::class, ApiModule::class]
ProfileComponent должен принимать не NetworkModule и ApiModule,  а AppComponent, который будет предоставлять зависимость ретрофита

2024-03-22 04:17 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/profile/di/ProfileComponent.kt
> +    modules = [ProfileModule::class, NetworkModule::class, ApiModule::class]
Что-то типо [такого](https://pastebin.com/y3LNMbhL)

2024-03-24 16:57 UTC, n-shvedov27 requested changes

2024-03-24 16:57 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/profile/di/ProfileComponent.kt
> +    modules = [ProfileModule::class, NetworkModule::class, ApiModule::class]
А зачем тебе NetworkModule и ApiModule?
 У тебя же AppComponent уже эти зависимости предоставляет

2024-03-24 17:13 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/feature/profile/di/ProfileComponent.kt
> +    modules = [ProfileModule::class, NetworkModule::class, ApiModule::class]
Взяла отсюда https://pastebin.com/y3LNMbhL

2024-03-24 17:39 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/profile/di/ProfileComponent.kt
> +    modules = [ProfileModule::class, NetworkModule::class, ApiModule::class]
Да, сорян
Скопипастил случайно не то

В общем по сути тебе эти два модуля тут не нужны
Зависимости из AppComponent получаем

2024-03-24 19:13 UTC, NadezhdaSakal commented on app/src/main/java/com/innoprog/android/feature/profile/di/ProfileComponent.kt
> +    modules = [ProfileModule::class, NetworkModule::class, ApiModule::class]
<img width="1440" alt="Снимок экрана 2024-03-24 в 22 13 09" src="https://github.com/InnoProg-Project/InnoProg/assets/79761587/97d63d57-9047-4da9-b154-c7a6eb40916c">

2024-03-26 05:26 UTC, n-shvedov27 approved these changes

2024-03-26 05:26 UTC, merged