80 Room
InnoProg-Project/my_startup pull request #89
Opened 2024-03-25 12:24 UTC by TanyaRul

2024-03-26 06:17 UTC, n-shvedov27 requested changes

2024-03-26 06:17 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/db/RoomDBModule.kt
> +    fun provideFavoritesInteractor(favoritesRepository: FavoritesRepository): FavoritesInteractorImpl {
NewsEntityMapper, FavoritesRepositoryImpl, FavoritesInteractorImpl должны быть в FeedModule

2024-03-26 06:17 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/db/RoomDBModule.kt
> +        return NewsEntityMapper()
Если добавить мапперу @Inject constructor, то его ни в каких модулях можно не указывать

2024-03-26 06:17 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/di/AppComponent.kt
> +    fun favoritesInteractor(): FavoritesInteractor
AppComponent не должен провайдить ни репозитории и интеракторы

2024-03-26 06:17 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/feed/data/db/NewsEntity.kt
> +data class AuthorEntity(
Этот класс где-то используется?

2024-03-26 06:17 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/feed/data/db/NewsEntity.kt
> +data class CompanyEntity(
И этот

2024-03-26 06:17 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/utils/NewsEntityMapper.kt
> +class NewsEntityMapper {
Почему этот маппер не в feature/feed?

2024-03-26 06:17 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/utils/NewsEntityMapper.kt
> +    /*private fun createAuthor(authorEntity: AuthorEntity): Author {
Зачем тут закомментированный код?

2024-03-27 07:55 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/utils/NewsEntityMapper.kt
> +    /*private fun createAuthor(authorEntity: AuthorEntity): Author {
Сделала используемым

2024-03-27 07:55 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/utils/NewsEntityMapper.kt
> +class NewsEntityMapper {
Перенесла

2024-03-27 07:55 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/feature/feed/data/db/NewsEntity.kt
> +data class CompanyEntity(
Сделала используемым

2024-03-27 07:55 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/feature/feed/data/db/NewsEntity.kt
> +data class AuthorEntity(
Сделала используемым

2024-03-27 07:55 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/di/AppComponent.kt
> +    fun favoritesInteractor(): FavoritesInteractor
Удалила, но не могу разобраться, что и куда нужно ещё добавить. Постоянно получаю ошибку: Dagger/MissingBinding] com.innoprog.android.db.RoomDB cannot be provided without an @Provides-annotated method. (https://pastebin.com/KQqNi6mp) Пробовала разные подходы из изученных примеров, но там в основном делают дополнительный класс App, AppModule и модули по слоям архитектуры (выглядит немного проще :) ). Мы такой подход не будем использовать, насколько я понимаю?

2024-03-27 07:55 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/db/RoomDBModule.kt
> +        return NewsEntityMapper()
Добавила

2024-03-27 07:55 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/db/RoomDBModule.kt
> +    fun provideFavoritesInteractor(favoritesRepository: FavoritesRepository): FavoritesInteractorImpl {
Здесь удалила, в FeedModule они есть через Binds

2024-03-28 06:23 UTC, n-shvedov27 requested changes

2024-03-28 06:23 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/feed/utils/NewsEntityMapper.kt
А почему он не в com.innoprog.android.feature.feed.data?

2024-04-02 05:23 UTC, n-shvedov27 requested changes
Починил инжект рума
Осталось пофиксить AuthorEntity внутри NewsEntity

2024-04-02 13:01 UTC, TanyaRul commented on app/src/main/java/com/innoprog/android/feature/feed/utils/NewsEntityMapper.kt
Перенесла

2024-04-03 04:02 UTC, n-shvedov27 approved these changes

2024-04-03 04:03 UTC, merged