43 create editing profile
InnoProg-Project/my_startup pull request #91
Opened 2024-03-25 14:44 UTC by Bivis63

2024-03-26 05:57 UTC, n-shvedov27 requested changes

2024-03-26 05:57 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/editingprofile/presentation/EditingProfileFragment.kt
> +        val dialog = Dialog(requireContext())
А эти диалоги почему не через навигацию?

2024-03-26 05:57 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/editingprofile/presentation/BottomSheetFragment.kt
> +class BottomSheetFragment : BottomSheetDialogFragment() {
Давай назовем его абстрактным BaseBottomSheetFragment 
C возможностью настраивать нужный layout
По сути как в BaseFragment
Жаль его в целом от BaseFragment наследовать не получится

2024-03-26 05:57 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/editingprofile/presentation/BottomSheetFragment.kt
> +class BottomSheetFragment : BottomSheetDialogFragment() {
Ну и вынести его в папку base
А сюда добавить реализацию

2024-03-26 05:57 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_editing_profile.xml
> +            app:buttonType="def"
Ты же вроде хотел добавить настройку цвета текста кнопки

2024-03-26 05:57 UTC, n-shvedov27 commented on app/src/main/res/navigation/auth_nav_graph.xml
> +    app:startDestination="@id/editingProfileFragment">
Я не смогу эту в dev слить
editingProfileFragment должен открываться через ProfileFragment

2024-03-26 05:57 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/editingprofile/presentation/EditingProfileFragment.kt
> +package com.innoprog.android.feature.editingprofile.presentation
Я бы лучше так пекеджи расположил
<img width="364" alt="Снимок экрана 2024-03-26 в 10 53 41" src="https://github.com/InnoProg-Project/InnoProg/assets/37715977/c4422d99-7007-4fc5-9027-1ba6f5e7a9b6">

2024-03-26 05:57 UTC, n-shvedov27 commented on uikit/src/main/res/values/strings.xml
> +    <string name="delete">Удалить</string>
Не углядел
Строки нужные для конкретной фичи не должны быть в uikit'е

Добавь плз в app файл
editprofile_string.xml

И туда складывай нужные строки

2024-03-27 05:41 UTC, n-shvedov27 requested changes
Конфликты

2024-03-28 06:33 UTC, n-shvedov27 requested changes

2024-03-28 06:33 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgButtonView.kt
> +            ButtonType.DELETE -> {
Давай лучше сделаем проставление цвета кнопки через отдельный метод, а не еще один ButtonType

2024-03-28 06:33 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_editing_profile.xml
> +        <androidx.appcompat.widget.Toolbar
Почему не InnoProgTopBarView?

2024-03-28 18:07 UTC, Bivis63 commented on app/src/main/res/layout/fragment_editing_profile.xml
> +        <androidx.appcompat.widget.Toolbar
мне кажется она не очень похожа на то что на макете )

2024-03-28 20:35 UTC, Bivis63 commented on app/src/main/res/layout/fragment_editing_profile.xml
> +        <androidx.appcompat.widget.Toolbar
поставил кастомный, но очень странно что по макету все размеры и стили сходятся а шрифт выглядит как то иначе

2024-03-28 20:35 UTC, Bivis63 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgButtonView.kt
> +            ButtonType.DELETE -> {
добавил

2024-03-29 05:31 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_editing_profile.xml
> +        <androidx.appcompat.widget.Toolbar
Завел задачку на это
https://github.com/InnoProg-Project/InnoProg/issues/95

2024-03-29 05:32 UTC, n-shvedov27 approved these changes

2024-03-29 05:32 UTC, merged