42 41 profile screen
InnoProg-Project/my_startup pull request #92
Opened 2024-03-26 14:48 UTC by NadezhdaSakal

1. Пока только вёрстка (без коннекта с апи, адаптера и вьюхолдера), чтобы Серега мог слить свою  часть
2. Есть проблема с чипами  (отображаются не так как в сэмпле и макете)

2024-03-27 05:40 UTC, n-shvedov27 requested changes

2024-03-27 05:40 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_profile.xml
> +    <HorizontalScrollView
А разве сами InnoProgChipGroupView скроллиться не умеют?

2024-03-27 05:40 UTC, n-shvedov27 commented on app/src/main/res/anim/scale.xml
Давай какое-то более информативное название для анимации сделаем?
Типо open_bottom_sheet

2024-03-27 05:40 UTC, n-shvedov27 commented on app/src/main/res/drawable/ic_document_multiple.xml
Давай эту иконку в uikit вынесем

2024-03-27 05:40 UTC, n-shvedov27 commented on app/src/main/res/drawable/ic_edit.xml
И эту

2024-03-27 05:40 UTC, n-shvedov27 commented on app/src/main/res/drawable/ic_info.xml
И эту

2024-03-27 05:40 UTC, n-shvedov27 commented on app/src/main/res/drawable/ic_more.xml
И эту

2024-03-27 05:40 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_profile.xml
> +    <androidx.appcompat.widget.Toolbar
А почему не InnoProgTopBarView?

2024-03-27 06:06 UTC, NadezhdaSakal commented on app/src/main/res/layout/fragment_profile.xml
> +    <HorizontalScrollView
нет

2024-03-27 07:40 UTC, NadezhdaSakal commented on app/src/main/res/layout/fragment_profile.xml
> +    <androidx.appcompat.widget.Toolbar
когда применяю nnoProgTopBarView строка в топБаре уползает влево, а не по центру

2024-03-27 11:21 UTC, NadezhdaSakal commented on app/src/main/res/layout/fragment_profile.xml
> +    <androidx.appcompat.widget.Toolbar
проблему со смещением текста в  топбаре я решила, костыльно, но решила

2024-03-28 05:53 UTC, n-shvedov27 requested changes

2024-03-28 05:53 UTC, n-shvedov27 commented on uikit/src/main/java/com/innoprog/android/uikit/InnoProgTopBarView.kt
> +    val rightIconIV by lazy { findViewById<ImageView>(R.id.right_icon) }
Давай лучше доставим rightIconIV private и просто добавим метод setOnRightIconClickListener

2024-03-28 06:52 UTC, n-shvedov27 approved these changes

2024-03-28 07:02 UTC, merged