32  screen login верстка экрана
InnoProg-Project/my_startup pull request #98
Opened 2024-03-31 12:20 UTC by AntaOtk

пока только ui

2024-04-01 06:44 UTC, n-shvedov27 requested changes

2024-04-01 06:44 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/presentation/AuthorizationFragment.kt
> +    private fun renderIVPassword() {
По-моему эта штука не работает

https://github.com/InnoProg-Project/InnoProg/assets/37715977/4e6febe0-b325-48d0-95b8-d270dafdf624

2024-04-01 06:44 UTC, n-shvedov27 commented on uikit/src/main/res/values/styles.xml
> +    <style name="ImageStyle_Corners_Rounded">
А для чего это в styles выносить?

2024-04-01 06:44 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/presentation/AuthorizationViewModel.kt
> +    private var inputPassword: String? = null
Эти поля где-то используются?

2024-04-01 06:44 UTC, n-shvedov27 commented on app/src/main/java/com/innoprog/android/feature/training/data/TrainingListRepositoryImpl.kt
> +    private val models =
Старайся без надобности не вносить изменения в файлы
Это увеличивает дифф ПРа

2024-04-01 06:44 UTC, n-shvedov27 commented on app/src/main/res/values/strings.xml
> +    <string name="hello">Добро пожаловать!</string>
Давай добавим префикс fragment_authorization... к строкам
Иначе скоро тут не разобраться будет

fragment_authorization_hello например

2024-04-01 17:54 UTC, AntaOtk commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/presentation/AuthorizationFragment.kt
> +    private fun renderIVPassword() {
добавила TransformationMethod. теперь работает

2024-04-01 18:07 UTC, AntaOtk commented on app/src/main/java/com/innoprog/android/feature/auth/authorization/presentation/AuthorizationViewModel.kt
> +    private var inputPassword: String? = null
убрала

2024-04-01 18:20 UTC, AntaOtk commented on uikit/src/main/res/values/styles.xml
> +    <style name="ImageStyle_Corners_Rounded">
наверно я туплю не очень понимаю как это без вынесения в стили прописывается в xml. или прописать скругление в коде тогда?

2024-04-03 04:06 UTC, n-shvedov27 requested changes
Билд упал

2024-04-04 05:53 UTC, n-shvedov27 approved these changes

2024-04-04 05:57 UTC, merged